name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]

    env:
      CODECEPTION_VERSION: 'dev-phpunit-10 as 4.1.99'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Prepare dependencies
        run: |
          wget https://robo.li/robo.phar
          php robo.phar prepare:dependencies
          composer update
          php robo.phar prepare:tests
          php robo.phar prepare:test-autoloading
          composer dump-autoload

      - name: Run test suite
        run: |
          php ./codecept run -c vendor/codeception/module-asserts/
          php ./codecept run unit -g core
          php ./codecept run cli